---
# Adapted from NYPL-Simplified instructions "Deployment: Quickstart with Docker" 
# https://github.com/NYPL-Simplified/Simplified/wiki/Deployment:-Quickstart-with-Docker#on-the-host-server

# Either the 'scripts' or the 'deploy' container can be run first; however, whichever is
# first should have the SIMPLIFIED_DB_TASK value of 'init'; the other should be 'migrate'

- name: Ensure circ-scripts docker container is started
  docker_container:
    name: circ-scripts
    image: "nypl/circ-scripts:{{ simplye_circulation_version }}"

    networks:
      - name: "{{ network_name }}"
    purge_networks: yes

    restart_policy: "unless-stopped"
    volumes:
      - /etc/libsimple:/etc/circulation
    env:
      TZ="{{ system_timezone }}"
      SIMPLIFIED_DB_TASK='init'
      SIMPLIFIED_PRODUCTION_DATABASE='postgres://{{ psql_username }}:{{ psql_password }}@{{ psql_endpoint }}:5432/{{ psql_db_name }}'
      TERM='xterm'
    detach: True
    state: started
