---
# Adapted from NYPL-Simplified instructions "Deployment: Quickstart with Docker" 
# https://github.com/NYPL-Simplified/Simplified/wiki/Deployment:-Quickstart-with-Docker#on-the-host-server

- name: Ensure circ-scripts docker container is started
  docker_container:
    name: circ-scripts
    image: "nypl/circ-scripts:{{ simplye_circulation_version }}"

    networks:
      - name: "{{ network_name }}"
    purge_networks: yes

    restart_policy: "unless-stopped"
    volumes:
      - /etc/libsimple:/etc/circulation
    env:
      TZ="{{ system_timezone }}"
      SIMPLIFIED_DB_TASK='migrate'
      SIMPLIFIED_PRODUCTION_DATABASE='postgres://{{ psql_username }}:{{ psql_password }}@{{ psql_endpoint }}:5432/{{ psql_db_name }}'
    detach: True
    state: started

