---
# Basic host configuration tasks

- name: Configure host users and utilities
  hosts: all
  become: yes
  vars_files:
    - vars/linode_vars.yml

  tasks:
    # With the actual yum_repository module
    - name: Add the EPEL repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    # Loop through utilities list
    - name: Install system utilities
      yum:
        pkg: "{{ item }}"
        update_cache: yes
        disable_gpg_check: yes
        state: present
      with_items:
        - htop
        - tmux
        - python-pip

    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade        

    # Add admin user (not root) with sudo privileges
    - name: Add administrative user for remote login
      user:
        name: "{{ admin_username }}"
        groups: wheel
        append: yes
        shell: /bin/bash
        createhome: yes
        password: "{{ admin_password }}"
        state: present
