- name: Ensure AWS resources are provisioned
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - libsimple-aws-objects

- name: Ensure Library Simplified components are deployed
  hosts: circulation-servers
  remote_user: "{{ ec2_initial_user }}"
  become: yes
  vars:
    - psql_endpoint: "{{ hostvars['localhost']['psql_endpoint'] }}"
  roles:
    - geerlingguy.docker
    - libsimple-host-aws
    - libsimple-container-circ-scripts
    - libsimple-container-circ-deploy

- name: Check whether a manual configuration file exists locally
  local_action: stat path="./provision-temp.yml"
  register: temp_plays
  
- import_playbook: provision-temp.yml
  when: temp_plays.stat.exists