- name: Ensure AWS resources are provisioned
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - libsimple-aws-objects

- name: Ensure Library Simplified components are deployed
  hosts: circulation-servers
  remote_user: "{{ ec2_initial_user }}"
  become: yes
  vars:
    - psql_endpoint: "{{ hostvars['localhost']['psql_endpoint'] }}"
  roles:
    - geerlingguy.docker
    - libsimple-host-aws
    - libsimple-container-circ-scripts
    - libsimple-container-circ-deploy

- name: Add temporary utilities to support the Circulation Manager if playbook exists
  hosts: circulation-servers
  remote_user: "{{ ec2_initial_user }}"
  become: yes

  vars_files:
    - vars/temp_vars.yml
    - group_vars/all/main.yml

  tasks:
    - name: Check whether a manual configuration file exists locally
      local_action: stat path=temporary-tasks.yml
      register: temp_plays

    - include: temporary-tasks.yml
      when: temp_plays.stat.exists

