---
# Shell playbook for adding temporary system tasks to the Circulation Manager

- name: Add temporary utilities to support the Circulation Manager if playbook exists
  hosts: all
  become: yes

  vars_files:
    - vars/temp_vars.yml
    - group_vars/all/main.yml

  tasks:
    - include: temporary-tasks.yml
