---
# Temporary provisioning tasks for the Circulation Manager
#
# Used until similar official Circulation Manager features are added

- name: Add temporary utilities to support the Circulation Manager
  hosts: all
  vars_files:
    - vars/temp_vars.yml

  tasks:
    - set_fact:
        psql_endpoint: "{{ hostvars['localhost']['psql_endpoint'] }}"
      when: hostvars['localhost']['psql_endpoint'] is defined
      
    - set_fact:
        psql_endpoint: "172.17.0.3"
      when: hostvars['localhost']['psql_endpoint'] is not defined
      
    - name: Create an Adobe registration parameters script, with host and DB info 
      template:
        src: "temp/export_lib_registry_values.j2"
        dest: "/root/export_lib_registry_values"
        owner: root
        group: root
        mode: 0770

    - name: Create a script to start Docker containers
      template:
        src: "temp/start_cm_containers.j2"
        dest: "/root/start_cm_containers"
        owner: root
        group: root
        mode: 0770

    - name: Create a script to stop Docker containers
      template:
        src: "temp/stop_cm_containers.j2"
        dest: "/root/stop_cm_containers"
        owner: root
        group: root
        mode: 0770

    - name: Create a cron task to restart the Circulation Manager containers after a reboot
      cron:
        name: "Restart Circulation Manager"
        cron_file: temporary_cm
        special_time: reboot
        user: root
        job: "/root/start_cm_containers"
