---
# Initial draft of provisioning a Linode using Ansible playbook alone.
# There is a distribution failure in testing, which may be related to the
# Linode API update to v4:
#   the distribution ID changes from integer to string
# The include plays below are also untested

- name: Create simple test Linode
  hosts: localhost
  vars_files:
    - vars/linode_vars.yml

# For testing, use tasks section below; ultimately should include as a role.
# See initial roles/libsimple-linode-create/tasks/main.yml.sample,
# which includes specific linode feature values not specified below.
  tasks:
    - local_action:
        module: linode
        api_key: "{{ linode_api_key }}"
        name: "{{ linode_name }}"
        plan: {{ plan_id }}
        datacenter: {{ datacenter_id }}
        distribution: "{{ distribution_name }}"
        password: "{{ root_password }}"
#        private_ip: yes    # Only in v2.3
        ssh_pub_key: "ssh-rsa {{ root_ssh_keyname }}"
        swap: {{ swap_size }}
        wait: yes
        wait_timeout: 600
        state: present

# Run the playbook that configures the host
- include: linode-configure.yml

# Run the playbook that installs all SCM services on one server:
- include: provision-vagrant.yml
