---
# Adapted from NYPL-Simplified instructions "Deployment: Quickstart with Docker" 
# https://github.com/NYPL-Simplified/Simplified/wiki/Deployment:-Quickstart-with-Docker#elasticsearch-optional-support-container

- name: Ensure elasticsearch docker container is started
  docker_container:
    name: es
    image: elasticsearch:1

    networks:
      - name: "{{ network_name }}"
        ipv4_address: "{{ elasticsearch_ip }}"
    purge_networks: yes

    restart_policy: "unless-stopped"
    detach: True
    state: started
  
- name: Verify IP address of elasticsearch docker container names 'es'
  shell: "docker inspect -f '{''{range .NetworkSettings.Networks}''}''{''{.IPAddress}''}''{''{end}''}' es"
  register: docker_inspect_es_ip
  
- name: Set variable es_docker_container_ip used later in config.j2 template
  set_fact: 
    elasticsearch_endpoint: "{{ docker_inspect_es_ip.stdout }}"

