---
# Adapted from NYPL-Simplified instructions "Deployment: Quickstart with Docker" 
# https://github.com/NYPL-Simplified/Simplified/wiki/Deployment:-Quickstart-with-Docker#on-the-host-server

- name: Ensure circ-deploy docker container is started
  docker_container:
    name: circ-deploy
    image: nypl/circ-deploy:2.0.1

    ports:
      - 80:80
    volumes:
      - /etc/libsimple:/etc/circulation
    env:
      SIMPLIFIED_DB_TASK='migrate'
      SIMPLIFIED_PRODUCTION_DATABASE='postgres://{{ psql_username }}:{{ psql_password }}@{{ psql_endpoint }}:5432/{{ psql_db_name }}'
    detach: True
    state: started

